logo: # add logo name
title: travelaround
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/travelaround" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email:  # your email
phone:  # your pnone number
website: https://dwayne.example.com # you website


# Paginate
paginate: 9
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
